# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 19:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gennotes_server', '0003_editingapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
